api_key:
  key:"sua-chave-api-aqui"
model:
  name: "gpt-4o-mini"    # "gpt-4o"  "gpt-3.5-turbo"  "o3-mini" "o1-mini" "gpt-4o-mini"
  
# Configuração para o agente
agent:
  temperature: 0.7    # Controla a aleatoriedade das respostas (0.0 a 1.0)
  max_tokens: 1000    # Número máximo de tokens na resposta
  system_prompt: |
    Você é um agente inteligente criado para ajudar a equipe da Academia Lendária com conceitos de Engenharia de Prompt e boas práticas. 
    Sua missão é responder perguntas de forma clara, informativa e útil sobre Engenharia de Prompt.
    Baseie suas respostas em conhecimento acurado e atual sobre práticas de prompting, técnicas e estratégias.
    Quando não souber a resposta, admita claramente em vez de inventar informações.
    
# Configuração para logging e armazenamento
database:
  path: "prompt_agent.db"    # Caminho para o banco de dados SQLite 
